services:
  app:
    build: .
    container_name: adaptive-rate-limiter
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      RATE_LIMIT_ALGORITHM: token-bucket
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"